sudo: required
dist: precise
language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-22
    - android-24
    - android-25
    - android-28
    - build-tools-28.0.2
    - extra-android-m2repository

env:
  matrix:
    - API=android-24 ABI=armeabi-v7a

# Emulator Management: Create, Start and Wait
before_script:
  - android-update-sdk --components=sys-img-$ABI-$API --accept-licenses='android-sdk-license-[0-9a-f]{8}'
  - echo no | android create avd --force -n test -t $API --abi $ABI -c 100M
  - emulator -avd test -no-skin -no-window &
  - set +e

    bootanim=""
    failcounter=0
    timeout_in_sec=360

    until [[ "$bootanim" =~ "stopped" ]]; do
    bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
    if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
    || "$bootanim" =~ "running" ]]; then
    let "failcounter += 1"
    echo "Waiting for emulator to start"
    if [[ $failcounter -gt timeout_in_sec ]]; then
    echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
    exit 1
    fi
    fi
    sleep 1
    done

  - adb shell input keyevent 82 &

script:
  - ./gradlew Checkstyle
  - ./gradlew clean assemble
  - ./gradlew :app:assembleDebug
  - ./gradlew :app:connectedAndroidTest
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/


cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/